title: Charles 筆記
name: devlin329
url: "https://devlin329.github.io"
description: 技術筆記與學習紀錄

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

